name: Deploy to GCP

on:
  push:
    branches: [ "main" ]

env:
  GCP_PROJECT_ID:         ${{secrets.GCP_PROJECT_ID}}
  WRKL_ID_PROVIDER:       ${{secrets.WRKL_ID_PROVIDER}}
  GCP_SA_EMAIL:           ${{secrets.GCP_SA_EMAIL}}
  TERRAFORM_STATE_BUCKET: ${{vars.TERRAFORM_STATE_BUCKET}}
  TF_VAR_GCP_PROJECT_ID:  ${{secrets.GCP_PROJECT_ID}}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        token_format: 'access_token'
        workload_identity_provider: "${{env.WRKL_ID_PROVIDER}}"
        service_account: ${{env.GCP_SA_EMAIL}}

    # Setup gcloud sdk
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    # Confirm our gcloud command is working
    - name: 'Use gcloud CLI'
      run: 'gcloud info'      

    # initialize terraform after adding the state buckets to the config
    - name: terraform init
      id: init
      working-directory: ./terraform
      run: |
        sed -i "s|<TF_STATE_BUCKET>|$TERRAFORM_STATE_BUCKET|g" tf_backend_storage.tf
        sed -i "s|<TF_STATE_PREFIX>|$GITHUB_REPOSITORY|g" tf_backend_storage.tf
        terraform init

    # run a terraform plan
    - name: terraform plan
      id: plan
      working-directory: ./terraform
      run: terraform plan

    # run a terraform apply
    - name: terraform apply
      id: apply
      working-directory: ./terraform
      run: terraform apply -auto-approve
      